name: Daily Shopware Order Sync

on:
  schedule:
    - cron: "0 2 * * *"  # Runs at 02:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-orders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust if needed

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        env:
          SHOPWARE_CLIENT_ID: ${{ secrets.SHOPWARE_CLIENT_ID }}
          SHOPWARE_CLIENT_SECRET: ${{ secrets.SHOPWARE_CLIENT_SECRET }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "🔍 Checking environment variables..."
          echo "SHOPWARE_CLIENT_ID length: ${#SHOPWARE_CLIENT_ID}"
          echo "SHOPWARE_CLIENT_SECRET length: ${#SHOPWARE_CLIENT_SECRET}"
          echo "GOOGLE_SERVICE_ACCOUNT_JSON length: ${#GOOGLE_SERVICE_ACCOUNT_JSON}"

          if [[ -z "$SHOPWARE_CLIENT_ID" ]]; then
            echo "❌ ERROR: SHOPWARE_CLIENT_ID is not set!"
            exit 1
          fi
          if [[ -z "$SHOPWARE_CLIENT_SECRET" ]]; then
            echo "❌ ERROR: SHOPWARE_CLIENT_SECRET is not set!"
            exit 1
          fi
          if [[ -z "$GOOGLE_SERVICE_ACCOUNT_JSON" ]]; then
            echo "❌ ERROR: GOOGLE_SERVICE_ACCOUNT_JSON is not set!"
            exit 1
          fi

      - name: Set up Google Service Account
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" | jq . > service-account.json
          echo "✅ Google Service Account JSON successfully written to file."

      - name: Run script
        env:
          SHOPWARE_CLIENT_ID: ${{ secrets.SHOPWARE_CLIENT_ID }}
          SHOPWARE_CLIENT_SECRET: ${{ secrets.SHOPWARE_CLIENT_SECRET }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python shopware_API.py  # Replace with the actual script filename
